route:
  repeat_interval: 2h
  receiver: email-me
  routes:
    - match:
        alertname: EndpointDown
      receiver: email-me
 
receivers:
- name: email-me
  email_configs:
  - to: 'xxx@gmail.com'
    from: yyy@gmail.com
    smarthost: smtp.gmail.com:587
    auth_username: yyy@gmail.com
    auth_identity: yyy@gmail.com
    auth_password: zzzzzzz
    send_resolved: true

