version: '3'

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_blackbox
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command: --config.file=/etc/prometheus/prometheus.yml
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager_blackbox
    ports:
      - 9094:9093
    volumes:
      - ./alertmanager:/etc/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager_Mail.yml'
      - '--storage.path=/alertmanager'
    restart: unless-stopped
